### ISSUE TITLE
demo give error

### ISSUE THREAD

**Issue by loboere** [open-mmlab/PIA#12]
i try in 1024 image but give error

**Comment by LeoXing1996** [comment]
Hey @loboere, thanks for your interest in our project. Which demo are you referring to? [Openxlab's online demo](https://openxlab.org.cn/apps/detail/zhangyiming/PiaPia), or the Gradio demo running on your local machine?

If you mean the Openxlab demo, could you please provide the input image you used? If you are referring to the local Gradio demo, could you provide the error traceback?

**Comment by LeoXing1996** [comment]
Hey @loboere, we now support `scaled_dot_product_attention` for memory-efficient attention. Now you can animate 1024x1024 image with 16GB gpu memory. Please pull our newest code and try this feature. If you still have any problem, feel free to re-open this issue.
