### ISSUE TITLE
Training code release？

### ISSUE THREAD

**Issue by mayuelala** [open-mmlab/PIA#16]
nice work， do you have  plan to release the training code?

**Comment by JoshonSmith** [comment]
@LeoXing1996 nice work， do you have plan to release the training code?

**Comment by mayuelala** [comment]
Yeah，nice work， do you have plan to release the training code? @zengyh1900 @JoshonSmith @lindahua @hellock

**Comment by zengyh1900** [comment]
thank you for your interest. training code is here, https://github.com/open-mmlab/PIA/blob/main/train.py
