### ISSUE TITLE
Can PIA checkpoint be used in A1111 webui?

### ISSUE THREAD

**Issue by xpeng** [open-mmlab/PIA#18]
great work!
can we put PIA checkpoint into animatediff webui extention as some motion models or else?

**Comment by LeoXing1996** [comment]
@xpeng Unfortunately, the animatediff extention cannot load PIA right now. You can try requesting this feature in the corresponding extension's repository.

**Comment by johndpope** [comment]
Hello @LeoXing1996  - 
I got this working and now very keen to try with my other sd models. 
(i did stumble on just selecting a lora from list - and it was showing the models - and thus breaks things - that second list should be restricted to lora only)

given that this code seems to extend animatediff - can we just hot swap (take included directory) and replace the base animatediff-webui codebase and it should just work? https://github.com/continue-revolution/sd-webui-animatediff
 does heart of logic lie in side that? was interface changed? have to dig around. fyi @continue-revolution

**Comment by continue-revolution** [comment]
If someone can explain the difference this repo made to animatediff (from code level) then it is easy for me to support that, otherwise I have to study the source code and it’s gonna be too time consuming.

**Comment by johndpope** [comment]
@LeoXing1996  - is is possible to update your animatediff as much as possible to bring in line with upstream? 
I paste your code into upstream and it seems like there's some regression
https://github.com/johndpope/AnimateDiff/pull/1/files
use_inflated_groupnorm

[animatediff/utils/util.py](https://github.com/johndpope/AnimateDiff/pull/1/files#diff-2534c6bf5d8734e70b21590cc8904628638fc8ce29f1060eb10dd4ee70d966bc)

animatediff/utils/convert_lora_safetensor_to_diffusers.py

[animatediff/utils/convert_from_ckpt.py](https://github.com/johndpope/AnimateDiff/pull/1/files#diff-a641fd374e83625e6de09dd46f63f4013123fa8cfef444c2325f8fff6215f006)

 is there a complication with PIA where it can't support controlnet?
