### ISSUE TITLE
pia.ckpt gdown url miss?

### ISSUE THREAD

**Issue by sunyuhan19981208** [open-mmlab/PIA#25]
is PIA gdown url missed? I can't download pia.ckpt and met such error:
```bash
requests.exceptions.MissingSchema: Invalid URL '1RL3Fp0Q6pMD8PbGPULYUnvjqyRQXGHwN': No scheme supplied. Perhaps you meant https://1RL3Fp0Q6pMD8PbGPULYUnvjqyRQXGHwN?
```

**Comment by ymzhang0319** [comment]
Hey @sunyuhan19981208, thx for your interest!

This can be caused by network.
You can also download pia.ckpt through https://openxlab.org.cn/models/detail/zhangyiming/PIA.

**Comment by sunyuhan19981208** [comment]
> Hey @sunyuhan19981208, thx for your interest!
> 
> This can be caused by network. You can also download pia.ckpt through https://openxlab.org.cn/models/detail/zhangyiming/PIA.

Thank you, there is another problem we met while trying your work, the face is easily collapse. Do you have any advice for me to solve the problem?
