### ISSUE TITLE
cannot download pia.ckpt file vid gdown

### ISSUE THREAD

**Issue by feiyangsuo** [open-mmlab/PIA#27]
command line
```
gdown --no-check-certificate 1RL3Fp0Q6pMD8PbGPULYUnvjqyRQXGHwN -O models/PIA/
```

error info
```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1RL3Fp0Q6pMD8PbGPULYUnvjqyRQXGHwN
```

maybe need to change the file's permmision?

ps: also cannot download the file via link in browser since my network is too unstable. so i'm trying to use gdown, got this problem

**Comment by ymzhang0319** [comment]
Hi @feiyangsuo, thx for your interest!

In fact, this link is public. Maybe you can try to download pia.ckpt through another link https://openxlab.org.cn/models/detail/zhangyiming/PIA.
