### ISSUE TITLE
Can you provide an extension to sdwebui or comfyui

### ISSUE THREAD

**Issue by guahunyo** [open-mmlab/PIA#28]
Can you provide an extension to sdwebui or comfyui

**Comment by zhangp365** [comment]
It's wonderful advice; comfyUI custom_node is absolutely necessary.

**Comment by zengyh1900** [comment]
Hi @guahunyo and @zhangp365,
PIA has been supported in comfyui !!! Please check this https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved
