### ISSUE TITLE
xFormers can't load C++/CUDA extensions. xFormers was built for:     PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.2+cpu)

### ISSUE THREAD

**Issue by guahunyo** [open-mmlab/PIA#30]
(pia) PS E:\PIA> python inference.py --config=example/config/majic_girl.yaml
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.2+cpu)

是我的xformers版本问题吗 还是cuda版本问题 如果需要降版本的话要降到哪个版本
我的CUDA是12.2.79
python: 3.10.8  
xformers: 0.0.21

**Comment by ymzhang0319** [comment]
你好@guahunyo，似乎是因为你的pytorch是cpu的。
下载一个cuda版本的pytorch也许可以解决。可以参考官网，下载一个相应版本的：https://pytorch.org/get-started/locally/
