### ISSUE TITLE
缺少模型下载地址

### ISSUE THREAD

**Issue by fallbernana123456** [open-mmlab/PIA#39]
models/DreamBooth_LoRA/cyberpunk.safetensors
models/DreamBooth_LoRA/genshin.safetensors

这2个是在哪里下载?

**Comment by LeoXing1996** [comment]
Thank you for your interest in our work, and I apologize for the delayed response.

`cyberpunk.safetensors` is not used in our example, and you can download `genshin.safetensors` from `https://civitai.com/models/108649/genshin-impact-all-in-one-or-character-lora-43336`
