### ISSUE TITLE
Please create demo colab

### ISSUE THREAD

**Issue by G-force78** [open-mmlab/PIA#4]
I am unable to get it to work based off the install instructions

Traceback (most recent call last):
  File "/content/PIA_env/PIA/inference.py", line 10, in <module>
    from animatediff.pipelines import I2VPipeline
  File "/content/PIA_env/PIA/animatediff/pipelines/__init__.py", line 1, in <module>
    from .i2v_pipeline import I2VPipeline
  File "/content/PIA_env/PIA/animatediff/pipelines/i2v_pipeline.py", line 10, in <module>
    from diffusers.loaders import IPAdapterMixin, TextualInversionLoaderMixin
ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (/usr/local/lib/python3.10/dist-packages/diffusers/loaders.py)

**Comment by LeoXing1996** [comment]
Hey @G-force78. You need install `diffusers==0.24.0` to run PIA. 
You can check your diffusers version by `pip list | grep diffusers` or `conda list diffusers`.

**Comment by darkzbaron** [comment]
+1

**Comment by G-force78** [comment]
Installed diffusers then got error 'no module torch._dynamo'

**Comment by LeoXing1996** [comment]
Hey @G-force78 and @darkzbaron, I found a third-party colab implementation: https://github.com/camenduru/PIA-colab, you may have a try.
