### ISSUE TITLE
Many packages missing, till now i found this file missing as well "diffusion_pytorch_model.bin" please help

### ISSUE THREAD

**Issue by Viper177** [open-mmlab/PIA#45]
I've installed the project following the provided guidelines. However, when I tried to create an animated image using the command given, I ran into errors indicating that several packages were missing. I installed some of them, but still encountered errors.

Currently, I am stuck on the following error. Please help me locating or providing this missing "bin" file

```
/miniconda3/envs/pia/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
loaded temporal unet's pretrained weights from models/StableDiffusion/unet ...
Traceback (most recent call last):
  File "/var/www/html/python/imageAnimator/inference.py", line 63, in <module>
    validation_pipeline = I2VPipeline.build_pipeline(
  File "/var/www/html/python/imageAnimator/animatediff/pipelines/i2v_pipeline.py", line 173, in build_pipeline
    unet = UNet3DConditionModel.from_pretrained_2d(
  File "/var/www/html/python/imageAnimator/animatediff/models/unet.py", line 554, in from_pretrained_2d
    raise RuntimeError(f"{model_file} does not exist")
RuntimeError: models/StableDiffusion/unet/diffusion_pytorch_model.bin does not exist
```
Please help

**Comment by Viper177** [comment]
how to uninstall this project along with all installed packages? This plugin seems not working and also broke some of my other scripts.

**Comment by zengyh1900** [comment]
Hi @Viper177,

Thanks for your interest, 
1. You need to follow [this step](https://github.com/open-mmlab/PIA?tab=readme-ov-file#download-checkpoints) to download necessary model weights
2. We suggest you install an environment for PIA from scratch and you can refer to this [yaml file](https://github.com/open-mmlab/PIA/blob/main/pia.yml).

**Comment by Viper177** [comment]
> Hi @Viper177,
> 
> Thanks for your interest,
> 
> 1. You need to follow [this step](https://github.com/open-mmlab/PIA?tab=readme-ov-file#download-checkpoints) to download necessary model weights
> 2. We suggest you install an environment for PIA from scratch and you can refer to this [yaml file](https://github.com/open-mmlab/PIA/blob/main/pia.yml).

Thanks @zengyh1900 

I installed all the packages listed in the readme. I'll try updating the project with this new YAML file.
