### ISSUE TITLE
models/mm_sd_v15_v2_full.ckpt

### ISSUE THREAD

**Issue by yuminnko** [open-mmlab/PIA#47]
Can I get the checkpoint "models/mm_sd_v15_v2_full.ckpt"?

**Comment by mamianshusheng** [comment]
> Can I get the checkpoint "models/mm_sd_v15_v2_full.ckpt"?

Hello, I met the same question! How did you find the `models/mm_sd_v15_v2_full.ckpt`? I can't find it anywhere in the Internet.
